version: 2
jobs:
  build:
    docker:
      - image: irof/circleci-openjdk-graphviz:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew build jig

      - run: sudo apt update && sudo apt install -y imagemagick fonts-ipafont
      - run: sudo mkdir converted
      - run: sudo convert -font /usr/share/fonts/opentype/ipafont-mincho/ipam.ttf build/jig/*.svg converted/*.png
      - run: sudo cp build/jig/*.xlsx converted

      - run: zip -r jig.zip build/jig
      - run: curl -Lo slackcat https://github.com/bcicen/slackcat/releases/download/v1.6/slackcat-1.6-$(uname -s)-amd64
      - run: sudo mv slackcat /usr/local/bin/
      - run: sudo chmod +x /usr/local/bin/slackcat
      - run: echo ${SLACK_TOKEN} > ~/.slackcat
      - run: for file in $(ls converted); do slackcat --channel ${SLACK_CANNEL} converted/${file}; done;

      - store_artifacts:
          path: build/jig/
          destination: jig
