version: 2
jobs:
  build:
    docker:
      - image: irof/circleci-openjdk-graphviz:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew build jig

      - run: zip -r {{ .Environment.CIRCLE_SHA1 }}-jig.zip build/jig
      - run:
        command: |
          curl -Lo slackcat https://github.com/bcicen/slackcat/releases/download/v1.6/slackcat-1.6-$(uname -s)-amd64
          sudo mv slackcat /usr/local/bin/
          sudo chmod +x /usr/local/bin/slackcat
          echo ${SLACK_TOKEN} > ~/.slackcat
          slackcat --channel ${SLACK_CANNEL} ./{{ .Environment.CIRCLE_SHA1 }}-jig.zip

      - store_artifacts:
          path: build/jig/
          destination: jig
