version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: sudo apt-get update && sudo apt-get install -y graphviz fonts-ipafont

      - checkout

      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build gradle jig

      - store_artifacts:
          path: build/jig/
          destination: jig
