version: 2
jobs:
  build:
    docker:
      - image: irof/circleci-openjdk:11-jdk-graphviz-imagemagick
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew build jig

      - run: sudo mkdir converted
      - run: sudo convert -font /usr/share/fonts/opentype/ipafont-mincho/ipam.ttf build/jig/package-relation-depth4.svg converted/package-relation-depth4.png
      - run: sudo convert -font /usr/share/fonts/opentype/ipafont-mincho/ipam.ttf build/jig/category.svg converted/category.png
      - run: sudo convert -font /usr/share/fonts/opentype/ipafont-mincho/ipam.ttf build/jig/category-usage.svg converted/category-usage.png
      - run: sudo convert -font /usr/share/fonts/opentype/ipafont-mincho/ipam.ttf build/jig/service-method-call-hierarchy.svg converted/service-method-call-hierarchy.png

      - run: curl -Lo slackcat https://github.com/bcicen/slackcat/releases/download/v1.6/slackcat-1.6-$(uname -s)-amd64
      - run: sudo mv slackcat /usr/local/bin/
      - run: sudo chmod +x /usr/local/bin/slackcat
      - run: echo ${SLACK_TOKEN} > ~/.slackcat

      - run: slackcat --channel ${SLACK_CANNEL} build/jig/business-rule.xlsx
      - run: slackcat --channel ${SLACK_CANNEL} build/jig/application.xlsx
      - run: for file in $(ls converted); do slackcat --channel ${SLACK_CANNEL} converted/${file}; done;

      - store_artifacts:
          path: build/jig/
          destination: jig
