version: 2
jobs:
  build:
    docker:
      - image: irof/circleci-openjdk-graphviz:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew build jig

      - store_artifacts:
          path: build/jig/
          destination: jig
